Woq/Woq/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('woquApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Woq/woquApp/urls.py
from django.urls import path
from . import news_view
from . import views

app_name = 'woquApp'

urlpatterns = [
    path('',news_view.index, name = 'index'),
    path("login/",views.login,name="login"),   #登录功能
    path('up_news/', news_view.up_news, name='up_news'),  # 发表动态
    path('news/', news_view.news, name='news'),  # 动态
    path('send/',views.send,name='send'),   # 点赞
    path('back/',views.back,name='back'),   # 撤回赞
    path('register/',views.register,name="register"),
    path('register1/',views.register1,name="register1"),
    path('detail/',views.detail,name="detail"),
    path('chat/',views.chat,name="chat"),
    path('zhuye/',views.zhuye,name="zhuye"),
    path('interest/',views.interest,name="interest"),
    path('comment/<nid>',views.comment,name="comment"),

]

Woq/woquApp/models.py
from django.db import models
from DB.Base_models import BaseModel
from django.contrib.auth.models import User

# Create your models here.

class News(BaseModel):
    uid = models.ForeignKey(to=User, on_delete=models.CASCADE,default='')
    con = models.CharField(max_length=800, verbose_name='用户动态内容')
    img = models.CharField(max_length=1000, verbose_name='用户动态图片')
    video = models.FileField(upload_to='video', verbose_name='视频')
    like_num=models.IntegerField(verbose_name='点赞数量',default=0)
    review_num=models.IntegerField(verbose_name='评论总数',default=0)
class Like(BaseModel):
    nid = models.ForeignKey(to=News, on_delete=models.CASCADE)
    uid = models.ForeignKey(to=User, on_delete=models.CASCADE)

class Review(BaseModel):
    nid = models.ForeignKey(to=News, on_delete=models.CASCADE,default='')
    uid = models.ForeignKey(to=User, on_delete=models.CASCADE,default='')
    con = models.CharField(max_length=300, verbose_name='访客回复内容')
    rep = models.CharField(max_length=300, verbose_name='作者回复内容', default='')

class Info(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=20, verbose_name='用户昵称')

Woq/woquApp/views.py
from django.contrib.auth import login as log
from woquApp.models import *
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from .news_view import *
from .form import Login
from .form import Register,Register1,CommentForm
from django.contrib.auth.models import User
from .models import Info,Review
import json


# Create your views here.

# 登录

@csrf_exempt
def login(request):
    if request.method == "GET":
        form = Login()
        return render(request,"woqu/login.html",{"form":form})
    else:
        form = Login(request.POST)
        if form.is_valid():
            log(request,form.user)
            reponse = redirect(reverse('woquApp:index'))
            reponse.set_cookie("name", form.cleaned_data["name"])
            return reponse
        else:
            return render(request,"woqu/login.html",{"form":form})


# 点赞
@csrf_exempt
def send(request):
    message='ok'
    uid = request.user.id
    nid=request.POST.get('nid',None)
    nid1=Like.objects.filter(nid_id=nid,uid_id=uid).first()
    like_num=News.objects.filter(id=nid).first().like_num
    like_num+=1
    if nid1 == None:
        Like.objects.create(nid_id=nid, uid_id=uid, is_del=1)
        News.objects.filter(id=nid).update(like_num=like_num)
    else:
        Like.objects.filter(uid_id=uid).update(is_del=1)
        News.objects.filter(id=nid).update(like_num=like_num)
    return HttpResponse(json.dumps({'message':message}))
# 取消点赞
@csrf_exempt
def back(request):
    message='ok'
    nid=request.POST.get('nid',None)
    uid = request.user.id
    Like.objects.filter(uid_id=uid).update(is_del=0)
    like_num = News.objects.filter(id=nid).first().like_num
    like_num -= 1

    News.objects.filter(id=nid).update(like_num=like_num)
    return HttpResponse(json.dumps({'message':message}))

# 加载注册界面
def register(request):
    if request.method=="POST":
        form = Register(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print("data:",data)
            phone=data['name']
            # return render(request, "woqu/register1.html", {'form': form,'phone':phone})
            return redirect(reverse("woquApp:register1"))
            # return render(request, "woqu/register.html", {'form': form})
        else:
            return render(request,"woqu/register.html",{'form':form})
    else:
        form = Register()
        return render(request,"woqu/register.html",{'form':form})

# 加载填写信息页面
def register1(request):
    if request.method=="POST":
        form = Register1(request.POST)

        if form.is_valid():
            data2 = form.cleaned_data
            # print("data2:", data2)
            nickname=data2['name']
            password=data2['password']
            phone=request.POST.get('phone',None)
            User.objects.create_user(username=phone,password=password)
            id=User.objects.filter(username=phone).first().id
            Info.objects.create(nickname=nickname,user_id=id)
            form = Login()
            return render(request, "woqu/login.html", {'form': form})
        else:
            return render(request, "woqu/register1.html", {'form': form})
    else:
        form2 = Register1()
        return render(request,"woqu/register1.html", {'form': form2})

def detail(request):
    username = request.user.username
    comment=Review.objects.all()
    print(comment)

    return render(request,'woqu/wx_detail.html',{'comment':comment,'username':username})

def comment(request, nid):
    print(nid)
    username=request.user.username
    uid=User.objects.filter(username=username).first().id
    if request.method=="GET":
        form=CommentForm()
        return render(request, 'woqu/wx_comment.html', {'form': form, 'nid': nid})
    else:
        form=CommentForm(request.POST)
        if form.is_valid():
            Review.objects.create(**form.cleaned_data,uid_id=uid,nid_id=nid)
            '''还需要news表   review_num +1 '''   #  <------------------------------------
            return redirect(reverse("woquApp:news"))
        return render(request,'woqu/wx_comment.html',{'form':form})

def zhuye(request):
    return render(request,'woqu/wx_zhuye.html')
def interest(request):
    return render(request,'woqu/interest.html')
def chat(request):
    return render(request,'woqu/chat_page.html')

Woq/woquApp/templates/woqu/dynamic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>动态</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'woqu/css/dynamic.css' %}">
    <link rel="stylesheet" href="{% static 'woqu/css/interest.css' %}">
    <script src="{% static 'woqu/js/rem.js' %}"></script>
    <script src="{% static 'woqu/js/jQuery.js'%}"></script>
</head>
<style>
    .top{width:auto;height:100%;justify-content:start;align-items: flex-end;}
    .top h4,.top h6{display:inline-block;width:auto;margin-right:.24rem;}
</style>
<body>

<header style="padding-bottom:.2rem;">
    <div class="top" style="margin-top:0;">
        <h4 style="font-size: 0.5rem;color: #555;">好友部落</h4>
        <h6 style="font-size: 0.28rem;color: #969696;">兴趣部落</h6>
        <h6 style="font-size: 0.28rem;color: #969696;">我的部落</h6>
    </div>
</header>
<section class="dynamic">
    {% for dat,val in data.items %}
        <main class="user_box">
            <div class="box_txt">
                <img src="{% static 'woqu/img/head.jpg' %}" alt="" class="user_head">
                <div class="user_des">
                    <span class="user_name">{{ val.0.info.nickname }}</span>
                    <p class="user_txt">{{ val.1.con }}</p>
                </div>
            </div>
            <!--<div class="box_video"></div>-->
            <div class="box_img">
                {% for img in val.2 %}
                <div><img src="/media/{{ img }}" alt="" class="dyn_imgs"></div>
                {% endfor %}
            </div>
            <div class="box_state">
                <div class="dyn_time"><div></div><span>{{ val.1.c_time }}</span></div>
                <div class="dyn_work">
                    {% if val.3 and val.4 %}
                    <div class="workes"><div class="works_icon like" id="nolike{{dat}}" flag="False" onclick="like({{dat}})"></div><span id="likenum{{dat}}">{{ val.1.like_num }}</span></div>
                    {% else %}
                    <div class="workes"><div class="works_icon like" id="nolike{{dat}}" flag="True" onclick="like({{dat}})" style="opacity:0.2;"></div><span id="likenum{{dat}}">{{ val.1.like_num }}</span></div>
                    {% endif %}
                    <div class="workes">
                        <a href="{% url 'woquApp:comment' dat %}"><div class="works_icon talk"></div></a><span>{{ val.1.review_num }}</span>
                    </div>
                    <div class="workes"><div class="works_icon share"></div></div>
                </div>
            </div>
            {% for i in con %}
            {% if i.nid_id == dat %}
            <div class="com">
                <h1 class="h1">最新评论</h1>
                <div class="comments">
                    <div class="nic">{{i.uid.info.nickname}}：</div>
                    <div class="neirong">{{i.con}}</div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </main>
    {% endfor %}
    <div class="new_dyn"><a href="{% url 'woquApp:up_news' %}" style="width:100%;height:100%;display:block;"></a></div>
</section>
<footer style="background: rgba(255,255,255,1)">
    <ul>
        <li><a href="{% url 'woquApp:chat' %}" class="foot_link">
            <div class="choice_img"><img src="{% static 'woqu/img/duihua_active.png' %}" alt=""></div>
            <span style="display: block;font-size: 0.18rem;margin-top: -0.55rem;margin-left: 0.05rem;color:#000;">对话</span></a>
        </li>
        <li><a href="{% url 'woquApp:interest' %}" class="foot_link">
            <div class="choice_img"><img src="{% static 'woqu/img/qvyou.png' %}" alt="" style="width: 0.32rem;height: 0.43rem;display: block;margin-top: 0.2rem"></div>
            <span style="display: block;font-size: 0.18rem;margin-top: -0.65rem;margin-left:-0.08rem;color: #969696;">趣友</span></a>
        </li>
        <li><a href="{% url 'woquApp:index' %}" class="foot_link">
            <div class="choice_img"><img src="{% static 'woqu/img/home.png' %}" alt="" style="width: 0.44rem;height: 0.44rem;display: block;margin-top: 0.2rem"></div>
            <span style="display: block;font-size: 0.18rem;margin-top: -0.65rem;margin-left: -0.03rem;color: #969696;">主页</span></a>
        </li>
        <li><a href="{% url 'woquApp:news' %}" class="foot_link">
            <div class="choice_img"><img src="{% static 'woqu/img/dongtai_active.png' %}" alt="" style="width: 0.38rem;height: 0.44rem;display: block;margin-top: 0.2rem"></div>
            <span style="display: block;font-size: 0.18rem;margin-top: -0.65rem;margin-left: -0.05rem;color:#ff577a;">动态</span></a>
        </li>
        <li><a href="" class="foot_link">
            <div class="choice_img"><img src="{% static 'woqu/img/wode.png' %}" alt="" style="width: 0.4rem;height: 0.44rem;display: block;margin-top: 0.2rem"></div>
            <span style="display: block;font-size: 0.18rem;margin-top: -0.65rem;margin-left: -0.05rem;color: #969696;">我的</span></a></li>
    </ul>
</footer>
<!--转发-->
<div class="zhuanfa">
    <div class="bgtp"></div>
    <div class="fot">
        <ul>
            <li class="click"><a href="#:;">
                <div class="tb"><img src="{% static 'woqu/img/qq.png' %}" alt=""></div>
                <div class="qq">QQ</div></a>
            </li>
            <li class="click"><a href="#:;">
                <div class="tb"><img src="{% static 'woqu/img/icon (32).png' %}" alt=""></div>
                <div class="qq">微信好友</div></a>
            </li>
            <li class="click"><a href="#:;">
                <div class="tb"><img src="{% static 'woqu/img/icon (20).png' %}" alt=""></div>
                <div class="qq">朋友圈</div></a>
            </li>
            <li class="click"><a href="#:;">
                <div class="tb"><img src="{% static 'woqu/img/icon (31).png' %}" alt=""></div>
                <div class="qq">微博</div></a>
            </li>
            <li class="click"><a href="#:;">
                <div class="tb"><img src="{% static 'woqu/img/icon (13).png' %}" alt=""></div>
                <div class="qq">举报该信息</div></a>
            </li>
            <li class="click"><a href="#:;">
                <div class="tb"><img src="{% static 'woqu/img/icon (12).png' %}" alt=""></div>
                <div class="qq">复制链接</div></a>
            </li>
        </ul>
    </div>
</div>
</body>
<script>
function like(id){
    let nid = id
    let num = parseInt($('#likenum'+id).text())
    flag = $('#nolike'+id).attr('flag')
    if(flag=='True'){
        $.ajax({
            url:"/send/",
            type:'post',
            dateType:'json',
            data:{'nid':nid},
            success:function(e){
                $('#nolike'+id).css('opacity','1').attr('flag',`False`)
                num+=1
                $('#likenum'+id).text(`${num}`)
            }
        })
    }else{
        $.ajax({
            url:"/back/",
            type:'post',
            dateType:'json',
            data:{'nid':nid},
            success:function(e){
                $('#nolike'+id).css('opacity','0.2').attr('flag',`True`)
                num-=1
                $('#likenum'+id).text(`${num}`)
            }
        })
    }
}
$('.share').click(function(){
    $('.zhuanfa').slideDown()
})
$('.click').click(function(){
    $('.zhuanfa').slideUp()
})
</script>
</html>

Woq/woquApp/templates/woqu/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>首页</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'woqu/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'woqu/css/interest.css' %}">
    <script src="{% static 'woqu/js/rem.js' %}"></script>
</head>
<style>
header{height:1.3rem;width:100%;padding:.3rem .24rem;box-sizing:border-box;background:none;}
.target{width:100%;font-family:PingFang;font-size:.2rem;color:rgba(0,0,0,.3);}
.h_bottom{width:100%;height:.78rem;display: flex;justify-content: space-between;align-items:flex-end;}
.h_bottom h1{font-size:.56rem;color:#fff;}
.mapicon{width:.3rem;height:.3rem;}
.foot_link{width:100%;height:100%;display:block;}
.box,.box img,.box1,.box2{width:5.34rem;height:9.21rem;position: absolute;bottom: -.01rem;margin: auto;left: 0;right: 0;overflow: hidden;border-radius:.08rem;z-index:15;}
.box1{width:4.86rem;background:rgba(253,75,126,0.7);bottom: .2rem;z-index:10;}
.box2{width:4.36rem;background:rgba(253,75,126,0.4);bottom: .4rem;z-index:5;}
</style>
<body>
<img src="{% static 'woqu/img/lovely.png' %}" alt="" class="bg">
<header>
    <div class="target">目标选择 ▶</div>
    <div class="h_bottom">
        <h1>兴趣好友</h1>
        <div>
            <img src="{% static 'woqu/img/map.png' %}" alt="" class="mapicon">
            <img src="{% static 'woqu/img/info.png' %}" alt="" class="mapicon">
        </div>
    </div>
</header>
<section class="roll">
    <div class="name"><h1>{{username}}</h1></div>
    <div class="box"><img src="{% static 'woqu/img/haha.png' %}" alt=""></div>
    <div class="box1"></div>
    <div class="box2"></div>
</section>
<footer style="background: rgba(0,0,0,0.2)">
    <ul>
        <li><a href="{% url 'woquApp:chat' %}" class="foot_link">
            <div class="choice_img"><img src="{% static 'woqu/img/talk01.png' %}" alt=""></div>
            <span style="display: block;font-size: 0.18rem;margin-top: -0.55rem;margin-left: 0.05rem;color: #969696;">对话</span></a>
        </li>
        <li><a href="{% url 'woquApp:interest' %}" class="foot_link">
            <div class="choice_img"><img src="{% static 'woqu/img/qvyou.png' %}" alt="" style="width: 0.32rem;height: 0.43rem;display: block;margin-top: 0.2rem"></div>
            <span style="display: block;font-size: 0.18rem;margin-top: -0.65rem;margin-left:-0.08rem;color: #969696;">趣友</span></a>
        </li>
        <li><a href="{% url 'woquApp:index' %}" class="foot_link">
            <div class="choice_img"><img src="{% static 'woqu/img/icon (41).png' %}" alt="" style="width: 0.44rem;height: 0.44rem;display: block;margin-top: 0.2rem"></div>
            <span style="display: block;font-size: 0.18rem;margin-top: -0.65rem;margin-left: -0.03rem;color: #ff577a;">主页</span></a>
        </li>
        <li><a href="{% url 'woquApp:news' %}" class="foot_link">
            <div class="choice_img"><img src="{% static 'woqu/img/dongtai.png' %}" alt="" style="width: 0.38rem;height: 0.44rem;display: block;margin-top: 0.2rem"></div>
            <span style="display: block;font-size: 0.18rem;margin-top: -0.65rem;margin-left: -0.05rem;color: #969696;">动态</span></a>
        </li>
        <li><a href="" class="foot_link">
            <div class="choice_img"><img src="{% static 'woqu/img/wode.png' %}" alt="" style="width: 0.4rem;height: 0.44rem;display: block;margin-top: 0.2rem"></div>
            <span style="display: block;font-size: 0.18rem;margin-top: -0.65rem;margin-left: -0.05rem;color: #969696;">我的</span></a>
        </li>
    </ul>
</footer>
</body>
</html>

Woq/woquApp/templates/woqu/login.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="{% static 'woqu/js/jQuery.js' %}"></script>
    <script src="{% static 'woqu/js/rem.js' %}"></script>
    <link rel="stylesheet" href="{% static 'woqu/css/login.css' %}">
    <title>登录页面</title>
</head>
<style>
    label{
        font-size:0.3rem;
        margin-left:0.35rem;
    }
    #id_name{
        width: 4.74rem;
        height: 0.8rem;
        outline: none;
        border: none;
        text-indent: 0.1rem;
        margin-left: 0.1rem;
    }
    #id_password{
        width: 4.74rem;
        height: 0.8rem;
        outline: none;
        border: none;
        text-indent: 0.1rem;
        margin-left: 0.1rem;
        margin-top:-0.9rem;
    }
    .loss_psw{
        margin-top:0.85rem;
    }
    .bottom{
        margin-top:0.3rem;
    }
    .login_box ul{
    width:2rem;
    height:0.3rem;
    padding:0;
    margin: 0 auto;
    background:none;
    }
    .login_box ul li{
        width:auto;
        height:0.3rem;
        font-size:0.2rem;
        line-height:0.3rem;
        color:red;
        text-align:center;
    }
</style>
<body>
    <div class="main">
        <div class="main_side">
            <div class="register">
                <a href="{% url 'woquApp:register' %}" class="register_btn">注册</a>
            </div>
            <div class="imgbox">
                <img src="{% static 'woqu/img/icon%20(7).png' %}" alt="">
            </div>
            <h4>Fun friend</h4>
            <h5 style="font-weight: bold">让聊天不尴尬 · 让玩耍不过站</h5>
            <div class="login_box" style="margin-top:0.3rem">
                <form action="{% url 'woquApp:login' %}" method="post">
                    {% csrf_token %}
                    {{ form }}

                    <button id="btn">立即登录</button>
                </form>
            </div>
            <div class="loss_psw">
                <span>·</span>&nbsp;密码丢失 点这里
            </div>
            <ul class="word_line">
                <li>
                    <span></span>
                </li>
                <li>第三方登录</li>
                <li>
                    <span></span>
                </li>
            </ul>
            <ul class="bottom">
                <li><img src="{% static 'woqu/img/loginQQ.png' %}" alt=""></li>
                <li><img src="{% static 'woqu/img/loginWX.png' %}" alt=""></li>
                <li><img src="{% static 'woqu/img/loginWB.png' %}" alt=""></li>
            </ul>
        </div>
    </div>
</body>
<script>
    let btn = $("#btn");
    let password=$('[name=password]');
    password.bind('input propertychange',function() {
        btn.css("background","-webkit-linear-gradient(left,#ff9682,#ff426b)");
        btn.css("color","white");
    });
</script>
</html>

Woq/woquApp/templates/woqu/news.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>发表动态</title>
    {% load static %}
    <script src="{% static 'woqu/js/jquery.js' %}"></script>
    <script src="{% static 'woqu/js/rem.js' %}"></script>
    <link rel="stylesheet" href="{% static 'woqu/css/wx_comment.css' %}">
    <link rel="stylesheet" href="{% static 'woqu/css/base.css' %}">

</head>
<body>
<div class="bg">
    <form action="{% url 'woquApp:up_news' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <header style="display:flex;justify-content: space-between;align-items: center;">
        <a href="{% url 'woquApp:news' %}"><div class="icon" style="margin:0;"></div></a>
        <button type="submit" class="_sub" style="font-size:.26rem;">发表</button>
    </header>
    <main style="padding:0 .24rem;">
        <div class="text">
            <textarea name="con" id="con" cols="30" rows="10" placeholder="在此处输入" style="height: 4rem;"></textarea>
            <div class="_show_img" id="img-box" style="overflow:hidden;"></div>
            <div class="box">
                <div class="add" style="position: relative;">
                    {{ form_img }}
                    <!--<input type="file" name="img_file" multiple class="_sub_file" onchange="lookImg(this)" accept="image/*">-->
                    <img src="{% static 'woqu/img/组7.png' %}" alt="">
                </div>
                <img src="{% static 'woqu/img/icon%20(6).png' %}" alt="">
                <img src="{% static 'woqu/img/icon%20(15).png' %}" alt="" onclick="clean_img()">
            </div>
        </div>
        <div class="map">
            <img src="{% static 'woqu/img/icon%20(28).png' %}" alt="">
            <h2>我的位置</h2>
        </div>
    </main>
    </form>
</div>
</body>
<script type="text/javascript">

function lookImg(obj) {
    var file = obj.files;
    var reader = new FileReader();
    for(var j=0;j<file.length;j++){
        var div;
        var reader= new FileReader();
        reader.readAsDataURL(file[j]);
        reader.onload=function(e){
            div=document.createElement('div');
            div.innerHTML='<img src="'+this.result+'" class="xmTanImg"/>';
            document.getElementById("img-box").appendChild(div);
        }
    }
}
function clean_img(){
    $('#id_img').val('')
    $('#img-box').html('')
    $('#con').val('')
}


</script>
</html>

Woq/woquApp/templates/woqu/register1.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'woqu/css/register.css' %}">
	<script src="{% static 'woqu/js/jQuery.js' %}"></script>
	<script src="{% static 'woqu/js/rem.js' %}"></script>
</head>
<style>
    .errorlist{
		position: fixed;
		font-size: 0.28rem;
		color: red;
	}
</style>
<body>
	<div class="main">
		<div class="back-box">
			<a href="{% url 'woquApp:register' %}">
				<img src="{% static 'woqu/img/icon (29).png' %}" alt="">
			</a>
		</div>
		<div class="tel-box">
			<p>
				<span class="circle"></span>
				您当前的手机号码设置为
			</p>
			<p id="tel">

			</p>
		</div>
		<div class="tel-set">
			<span>
				请为您的账号设置用户名以及密码
			</span>
			<span class="bar-box">
				<span class="bar"></span>
			</span>
		</div>
		<div class="phone-box user-pass">
			<form action="/register1/" method="post" autocomplete=off>
				<input type="hidden" id="phone" value="" name="phone">
				{% csrf_token %}
				{% for value in form.errors.values %}
                    {{ value }}
                {% endfor %}

				{{ form.errors }}
				<div class="input-box">
					<div class="verification-code">
						<img src="{% static 'woqu/img/user.png' %}" alt="">
					</div>
					<!--<input type="text" placeholder="请填写您的用户名">-->
					{{form.name}}
				</div>
				<div class="input-box">
					<div class="verification-code">
						<img src="{% static 'woqu/img/icon (24).png' %}" alt="">
					</div>
					<!--<input type="text" placeholder="请在此设置您的密码">-->
					{{form.password}}

				</div>
				<div class="input-box">
					<div class="verification-code">
						<img src="{% static 'woqu/img/icon (24).png' %}" alt="">
					</div>
					<!--<input type="text" placeholder="请再次输入您的密码">-->
					{{form.password2}}
				</div>

				<a class="next-btn" href="javascripts:;">
					<button type="submit" id="rgsbtn">确定</button>
				</a>
			</form>
		</div>

	</div>
</body>
<script>
	$("#tel").text(localStorage.getItem("tel"))
	$("#phone").val(localStorage.getItem("tel"))

</script>
</html>

Woq/woquApp/templates/woqu/wx_comment.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>详情</title>
    {% load static %}
    <script src="{% static 'woqu/js/jQuery.js' %}"></script>
    <script src="{% static 'woqu/js/rem.js' %}"></script>
    <link rel="stylesheet" href="{% static 'woqu/css/wx_comment.css' %}">
</head>
<body>
<div class="bg">
    <header>
        <a href="{% url 'woquApp:news' %}"><div class="icon"></div></a>
    </header>
    <form action="{% url 'woquApp:comment' nid %}" method="post">
    {% csrf_token %}
    <main>
        <div class="text">
            {{ form.con }}
            <!--<textarea name="" id="" cols="30" rows="10" class="con"></textarea>-->
            <h1 class="warning">在此处输出评论内容</h1>
            <div class="add">
                <img src="{% static 'woqu/img/组7.png' %}" alt="">
            </div>
            <img src="{% static 'woqu/img/icon (6).png' %}" alt="">
            <img src="{% static 'woqu/img/icon (15).png' %}" alt="" onclick="run()">
        </div>
        <div class="map">
            <img src="{% static 'woqu/img/icon (28).png' %}" alt="">
            <h2>我的位置</h2>
        </div>
    </main>
    <footer>
        <input type="text" placeholder="说出您想要说的话">
        <button type="submit" class="button"><img src="{% static 'woqu/img/jianpan.png' %}" alt=""></button>
    </footer>
    </form>
</div>
</body>
<script>
    $(function(){
        $('.con').focus(function(){
            $('.warning').css('display','none')
        });
        $('.con').blur(function(){
            $('.warning').css('display','block')
        })
    })
</script>
<script>
    function run(){
        $('#id_con').val('')
    }
</script>
</html>